### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by Mrsevic** [denis-peshkov/TypeScriptDefinitionGenerator#9] opened 2018-08-30 07:35 UTC
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: v2.2.0.97

### Description
Upon pressing the Generate typescript definition I receive an following error:
Could not load file or assembly:'Newtonsoft.Json, Version = 10.0.0.0, Culture neutral'... or one of it's dependencies. 
I could probably fix the error by rebuilding the source but..
### Steps to recreate
1. Right click on the *.cs vm file 
2. Pressing the Generate typescript definition command

### Current behavior
It is throwing an exception instead of generating the *.cs.d.ts file.

### Expected behavior
It should generate *.cs.d.ts file.

**Comment by denis-peshkov** [comment] 2018-09-04 12:12
Hi @Mrsevic, 
could you provide an example of .cs file which cause an a problem?

I can't reproduce it, by the way I wold like to help you.

**Comment by Mrsevic** [comment] 2018-09-07 06:26
Hi @denis-peshkov. Thank you for your time and swift response.

An typical example is an view model that has the following simple structure:
    [TypeScriptModule("ProjectName.Subdirectory.Server")]
  public class VMName
    {
        public ClassName[] classNames{ get; set; }

        [TypeScriptModule("ProjectName.Subdirectory.Server")]
        public class Struct
        {
            public string Id { get; set; }
            public bool Bool{ get; set; }

            public Prova(Prove.Prova s)
            {
                Id = s.Id;
                Bool = s.Activations.Bool;
            }
        }
    }
We utilize asp.net core 2.1 web application.
Regards,
Stefan Mrsevic

**Comment by denis-peshkov** [comment] 2018-09-07 08:47
I tried to reproduce the same situation, but can't (, sorry.

I created a file Class.cs
```c#
namespace WebApplication1
{
    public class VMName
    {
        public ClassName[] classNames { get; set; }

        public class Struct
        {
            public string Id { get; set; }
            public bool Bool { get; set; }

            public void Prova(Prove s)
            {
                Id = s.Id;
                Bool = s.Activations.Bool;
            }
        }
    }

    public class Prove
    {
        public string Id { get; set; }
        public Obbj Activations { get; set; }
    }

    public class Obbj
    {
        public bool Bool { get; set; }
    }

    public class ClassName
    {
    }
}
```

and get next Class.generated.ts
```ts
// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by TypeScript Definition Generator v2.2.0.97
// </auto-generated>
// ------------------------------------------------------------------------------
export interface Struct {
  Id: string;
  Bool: boolean;
}
export interface VMName {
  classNames: ClassName[];
}
export interface Prove {
  Id: string;
  Activations: Obbj;
}
export interface Obbj {
  Bool: boolean;
}
export interface ClassName {
}
```

Could you give an example of code that actually cause an error?

**Comment by Mrsevic** [comment] 2018-10-06 15:21
Sorry for not responding, somehow I missed out from the notification, the code structure was exactly like that. I'll try to analyze in depth from where does the problem actually comes from.

**Comment by denis-peshkov** [comment] 2018-10-12 09:34
could you give me the archive of the solution, where I can 100% reproduce it?

**Comment by denis-peshkov** [comment] 2018-10-20 10:41
@Mrsevic, so what will we do?
Close the issue?

**Comment by Mrsevic** [comment] 2018-10-20 14:28
I will try to set up an working solution. Sorry for not answering I am a little bit busy these days.

**Comment by denis-peshkov** [comment] 2018-10-22 11:08
well, I'm awaiting for the working solution, where I can reproduce the error.

**Comment by Mrsevic** [comment] 2018-10-22 12:38
This the default template with feature folders that I am always using, you can see the error on the ErrorViewModel:
https://github.com/artiomchi/AspNetWithFeatureFolders

P.S Maybe it would be good if you could rebase upon the latest commit from Mads on the base branch it would give an project an nice performance boost.

**Comment by gcecc** [comment] 2019-03-26 10:56
Hi, I'm facing the same issue; did anyone have a solution to this problem?

**Comment by gcecc** [comment] 2019-03-28 07:55
Solved updating Visual Studio to the last version

**Closed as completed** 2019-04-10 11:04 UTC
Labels: invalid
